version: "3.9"
services:
    mongodb:
        image: mongo:4.4.4
        container_name: db_container
        env_file: ./.env
        ports:
            - $MONGODB_DOCKER_PORT:$DB_PORT
        restart: always
        volumes:
            - mongodb:/data/db

    app:
        depends_on:
            - mongodb
        build: .
        restart: always
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        volumes:
            - .:/usr/src/app
        environment:
            - DB_HOST=mongodb
            - DB_NAME=$DB_NAME
            - DB_PORT=$DB_PORT
            - DB_AUTH=noAuth
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
        command: npm run dev
volumes:
    mongodb: {}